### ISSUE TITLE
Feature Request: Enable 'saves'

### ISSUE THREAD

**Issue by byronczimmer** [Auzzy/1846-routes-web#2]
After entering a fairly complicated map, 'error' was the only output from the route finder.
A refresh of the page (F5) wiped the map.

Having a way to save and restore state would be a first step towards being able to share board state on errors with the developer.

A save state could also allow asynchronous game play.

**Comment by Auzzy** [comment]
This was deployed in commit 51999e7c1daea789db7043adf575454d1b3fec77.

Whenever a change is made to the game state (tile placed, railroad or private company added, deleted, or updated), the state is saved in the browser. This state will be maintained even when you close the browser.

**Comment by Auzzy** [comment]
Had to back this change out due to odd interactions with the tile table.

**Comment by Auzzy** [comment]
Reimplemented change in 8f3808bdf14d787acc5b65b838ae497921728b03.

In short, I attempted to mix interacting with the Handsontable through its interface and through the underlying matrix. The reason was that I could get validation for free. But this left the table in a weird state, which only became apparent upon trying to delete a single tile, or certain sequences with the clear map button.

Instead, I do the validation myself, and load the data directly into the underlying matrix.
